vary raw authorization version added
bmstu-iu8-g1-2019-project/just-to-do-it pull request #1
Opened 2019-10-01 21:16 UTC by sergejkoll

2019-10-03 20:48 UTC, drewxa commented on main.go
> +	_, err = db.Exec("INSERT INTO objectuser (email, login, fullname, password, acc_verified) values ($1, $2, $3, $4, $5)",
objectuser ?

2019-10-03 20:48 UTC, drewxa commented on main.go
> +	_, err = db.Exec("INSERT INTO objectuser (email, login, fullname, password, acc_verified) values ($1, $2, $3, $4, $5)",
password в открытом виде?

2019-10-03 20:48 UTC, drewxa commented on main.go
> +	url := "localhost:3000/confirm/" + obj.Login
localhost ?

2019-10-03 20:48 UTC, drewxa commented on main.go
> +	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(obj.Password), 8)
э, пароль открытым текстом в json'e прилетает?

2019-10-03 20:48 UTC, drewxa commented on main.go
> +	err = smtp.SendMail("smtp.gmail.com:587", smtp.PlainAuth("", "kolesnikov.school4@gmail.com", "Proektk2019", "smtp.gmail.com"),
тут же нет пароля от почты, да?

2019-10-03 20:48 UTC, drewxa commented on main.go
> +	err := json.NewDecoder(r.Body).Decode(&received_object)
Body у Get ?

2019-10-05 23:20 UTC, Alex-Kuz commented on main.go
> +	"net/smtp"
Надо прибраться
Разделить на "внутренние" и "внешние" пакеты

2019-10-05 23:20 UTC, Alex-Kuz commented on main.go
> +	Acc_verified bool `json:"acc_verified"`
Надо camelCase.
Сам не фанат, но это соглашение.

2019-10-05 23:20 UTC, Alex-Kuz commented on main.go
> +	id int            `json:"id"`
Это точно работает с приватным полем?

2019-10-05 23:20 UTC, Alex-Kuz commented on main.go
> +	rows := db.QueryRow("SELECT * FROM objectuser WHERE login = $1", login)
```go
rows := row // *Row
```
В общем странно. Надо разобраться с типами.

2019-10-13 19:44 UTC, adkuz requested changes

2019-10-13 19:44 UTC, Alex-Kuz commented on main.go
> +        r.HandleFunc("/user/{id}", env.deleteUserHandler).Methods("DELETE")
Табуляция заболела.

2019-10-13 19:44 UTC, Alex-Kuz commented on main.go
> +	db, err := NewDB("postgres://postgres:pass@localhost/postgres")
Берите данные либо из ENV, либо из какого-нибудь файла конфигурации. 
Не надо хардкодить локалхосты.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/confirm.go
> +// Функция генерирует хэш
Договоритесь с коллегой, на каком языке вы пишете комментарии.
Но язык должен быть 1. Желательно EN.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/confirm.go
> +}
1. Довольно непонятное имя для функции. Можно сформулировать лаконично, но яснее.
2. Результат выполнения запроса никак не проверяется и не обрабатывается. Что, если записи не было?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/confirm.go
> +	hash = addressGenerator(login)
Вот тут не до конца ясна логика. Генерируется случайная строка, затем хешируется с логином. Все это нужно для того, чтобы человек не смог сгенерировать сам секрет, который вы положите в БД в таблицу для ожидающих подтверждения. Но соль не сохраняется. Вопрос - зачем такой сложный алгоритм, если можно просто сгенерировать случайный секрет и положить его в БД и отправить пользователю?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/confirm.go
> +	pass := "Proektk2019"
Кода мало, хардкода много.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/confirm.go
> +		url
Лучше строка с `%s` и затем форматирование с переменными.
Тогда строку можно будет вынести в константы пакета.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/controllers.go
> +		return
?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/env.go
> +        deleteUser(int) (error)
С табуляцией, видимо, систематическая проблема.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/env.go
> +	Acc_verified bool `json:"acc_verified"`
Используйте в именах переменных CamelCase, а в именах json - что хотите, я за snake_case.
Пока я вижу змею, которая съела верблюда.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/env.go
> +type Auth_confirmation struct {
И тут имя надо поправить.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +	row := db.QueryRow("SELECT * FROM usertab WHERE login = $1", login)
`usertab` - вам с командой стоит больше брейнштормить по поводу имен.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +	}
Может быть лучше сначала сделать запись в БД, а потом, в случае успеха, отправить подтверждение на почту?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +//confirm&hash=...
Ну вы поняли....

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +	_, err = db.Exec("UPDATE usertab SET acc_verified = $1 where login = $2", true, conf.Login)
Ну вот! Можете ведь нормальные имена таблиц придумывать!
Лайк, подписка.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/db/database.sql
> +    email varchar(64),
UNIQUE!

2019-10-13 19:44 UTC, Alex-Kuz commented on src/db/database.sql
> +    login varchar(32),
Может, лучше ID?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +func (db *DB) Confirm(hash string) (err error) {
Нет логики на просроченные подтверждения.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +	_, err = db.Exec("UPDATE usertab SET acc_verified = $1 where login = $2", true, conf.Login)
почему не `("UPDATE usertab SET acc_verified = true where login = $1", conf.Login)`?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/user/controllers.go
> +		http.Error(w, http.StatusText(404), 404)
Лучше сообщение ошибки возвращать в виде JSON-тела. Клиент сам определит, как это отобразить.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/user/controllers.go
> +		http.Error(w, http.StatusText(404), 404)
Это касается всех подобных моментов.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/user/services.go
> +	row := db.QueryRow("SELECT * FROM usertab WHERE id = $1", id)
Советую явно перечислять поля.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/user/services.go
> +		updateUser.Login, updateUser.Fullname, hashedPassword, updateUser.Acc_verified, id)
Надо ограничивать строку. Неудобно читать.
Переносите код на следующую строку, в этом нет криминала.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +func (db *DB) Login(login string) (obj User, err error) {
Так...а где пароль?

2019-10-13 19:44 UTC, Alex-Kuz commented on src/user/services.go
> +	}
У вас уже есть код, который это делает. Переиспользуйте его.

2019-10-13 19:44 UTC, Alex-Kuz commented on src/auth/services.go
> +	_, err = db.Exec("UPDATE usertab SET acc_verified = $1 where login = $2", true, conf.Login)
После подтверждения запись из `auth_confirmation` должна удаляться.
И желательно делать эти 2 операции в одной транзакции.

2019-10-15 15:32 UTC, sergejkoll commented on src/db/database.sql
> +    login varchar(32),
мы же вроде по логину договорились хэшировать ссылку по этому и хранил логин, но если надо могу исправить

2019-10-15 15:40 UTC, sergejkoll commented on src/auth/services.go
> +func (db *DB) Login(login string) (obj User, err error) {
Это функция просто возвращает объект типа User по такому логину, пароль проверяется в ResponseLoginHandler и сравнивается с тем который пришел в json'e и с тем который находится в бд и если не совпадают StatusUnauthorized.

2019-10-15 16:15 UTC, sergejkoll commented on src/user/services.go
> +	row := db.QueryRow("SELECT * FROM usertab WHERE id = $1", id)
А можно на примере понять зачем, а то я чет не понял((

2019-10-17 16:00 UTC, merged