CI/CD
bmstu-iu8-g1-2019-project/just-to-do-it pull request #2
Opened 2019-10-01 23:41 UTC by dankokin

2019-10-05 22:44 UTC, Alex-Kuz commented on Dockerfile
> +CMD go test
Довольно бесполезный сервер.
Он запустится, протестит себя и ... умрет.
Логика такая:
- Юнит тесты
- Модульные тесты (если имеет смысл)
- Билд докера
- Функциональное тестирование API (запросы на поднятый инстанс)
- Интеграционные тесты (если есть другие сервисы)
- 2e2, но об этом позже

2019-10-05 22:44 UTC, Alex-Kuz commented on main.go
> +	"os"
Тут надо прибраться.

2019-10-05 22:44 UTC, Alex-Kuz commented on main.go
> +	str string
awesome naming
А если серьезно, надо поправить.

2019-10-05 22:44 UTC, Alex-Kuz commented on main.go
> +	http.ListenAndServe(":" + os.Getenv("PORT"), nil)
Опасно. Надо проверять, что берешь из окружения.

2019-10-05 22:51 UTC, Alex-Kuz commented on main.go
> +		ob := new(Object)
Зачем?

2019-10-09 21:03 UTC, drewxa commented on src/services/task_service.go
> +			panic(err)
а тут точно panic?

2019-10-09 21:03 UTC, drewxa commented on src/services/task_service.go
> +		panic(err)
и тут?

2019-10-10 09:33 UTC, dankokin commented on src/services/task_service.go
> +			panic(err)
> а тут точно panic?
Мне тоже не понравилось, как вариант, можно возвращать пустой массив, тогда в контроллере это будет попадать под 404 ошибку. Норм?

2019-10-13 20:02 UTC, adkuz requested changes

2019-10-13 20:02 UTC, adkuz commented on server_test.go
> +	if expected != rec.Body.String() {
https://medium.com/@sebdah/go-best-practices-testing-3448165a0e18

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +func GetTaskByTaskIdHandler(w http.ResponseWriter, r* http.Request) {
Можно проще `GetTaskHandler`.
Не нужно джавить лишний раз.

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +	w.Header().Set("Content-Type", "application/json; charset=utf-8")
Эту строчку вы пишете каждый раз.
Декораторов в Го нет, но способы избавиться от повторения этой строки есть. 
Задача на подумать.

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +	taskId, _ := strconv.ParseInt(mux.Vars(r)["id"], 10, 64)
Опасно. Проверяйте ошибку.

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +	}
Вы нашли пользователя в базе данных, но не смогли на своей стороне его сериализовать в JSON.
Почему виноват пользователь то? BadRequest - это когда вы (как сервер) хотели число, а я послал вам строку.

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +func GetTaskByAssigneeIdIdHandler(w http.ResponseWriter, r *http.Request) {
Название функции не соответствует действительности.

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +	tasks := db.GetTaskByAssigneeId(assigneeId)
Аналогичная претензия.
Я вижу, как некоторая магическая функция возвращает одну задачу (по названию функции).

2019-10-13 20:02 UTC, adkuz commented on src/controllers/task_controller.go
> +func PostTask(w http.ResponseWriter, r *http.Request) {
Нужны комментарии или нормальное название.
Можно и одновременно.

2019-10-13 20:02 UTC, adkuz commented on src/db/database.sql
> +)
Комментарии. 
Сможете обосновать выбор типов, отвечающих за хранение строк и текста?
Вариантов много, смысла мало.

2019-10-13 20:02 UTC, Alex-Kuz commented on src/services/task_service.go
> +	rows, err := db.Query(query, id)
Кто-то не закрыл соединение...

2019-10-13 20:02 UTC, Alex-Kuz commented on src/services/task_service.go
> +	rows, err := db.Query(query, id)
Это суперважно.

2019-10-13 20:02 UTC, Alex-Kuz commented on src/services/task_service.go
> +			"($1, $2, $3, $4, $5, $6, $7, $8, $9)"
Я правильно вижу: константную строку вы каждый раз присваиваете переменной?

2019-10-17 15:37 UTC, merged